Realizando imports necessários

In [ ]:
import sys
!{sys.executable} -m pip install psycopg2
!{sys.executable} -m pip install sqlalchemy
!{sys.executable} -m pip install pandas 
!{sys.executable} -m pip install numpy

Lendo arquivo ocurrence.txt

In [15]:
import pandas as pd

df = pd.read_csv('occurrence.txt', sep='\t')
df

,gbifID,accessRights,bibliographicCitation,language,license,modified,publisher,references,rightsHolder,type,...,level0Gid,level0Name,level1Gid,level1Name,level2Gid,level2Name,level3Gid,level3Name,iucnRedListCategory,eventType
0,2365686427,Creative Commons Attribution Non Commercial (C...,NaN,NaN,CC_BY_NC_4_0,NaN,NaN,NaN,Museu Paraense Emílio Goeldi (MPEG),NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2365686418,Creative Commons Attribution Non Commercial (C...,NaN,NaN,CC_BY_NC_4_0,NaN,NaN,NaN,Museu Paraense Emílio Goeldi (MPEG),NaN,...,BRA,Brazil,BRA.10_1,Maranhão,BRA.10.59_2,Codó,NaN,NaN,NE,NaN
2,2365686416,Creative Commons Attribution Non Commercial (C...,NaN,NaN,CC_BY_NC_4_0,NaN,NaN,NaN,Museu Paraense Emílio Goeldi (MPEG),NaN,...,BRA,Brazil,BRA.10_1,Maranhão,BRA.10.52_2,Caxias,NaN,NaN,NE,NaN
3,2365686414,Creative Commons Attribution Non Commercial (C...,NaN,NaN,CC_BY_NC_4_0,NaN,NaN,NaN,Museu Paraense Emílio Goeldi (MPEG),NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2365686412,Creative Commons Attribution Non Commercial (C...,NaN,NaN,CC_BY_NC_4_0,NaN,NaN,NaN,Museu Paraense Emílio Goeldi (MPEG),NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,1438492475,Creative Commons Attribution Non Commercial (C...,NaN,NaN,CC_BY_NC_4_0,NaN,NaN,NaN,Museu Paraense Emílio Goeldi (MPEG),NaN,...,BRA,Brazil,BRA.14_1,Pará,BRA.14.78_2,Nova Ipixuna,NaN,NaN,NE,NaN
888,1438492474,Creative Commons Attribution Non Commercial (C...,NaN,NaN,CC_BY_NC_4_0,NaN,NaN,NaN,Museu Paraense Emílio Goeldi (MPEG),NaN,...,BRA,Brazil,BRA.14_1,Pará,BRA.14.78_2,Nova Ipixuna,NaN,NaN,NE,NaN
889,1438492473,Creative Commons Attribution Non Commercial (C...,NaN,NaN,CC_BY_NC_4_0,NaN,NaN,NaN,Museu Paraense Emílio Goeldi (MPEG),NaN,...,BRA,Brazil,BRA.14_1,Pará,BRA.14.78_2,Nova Ipixuna,NaN,NaN,NE,NaN
890,1438492472,Creative Commons Attribution Non Commercial (C...,NaN,NaN,CC_BY_NC_4_0,NaN,NaN,NaN,Museu Paraense Emílio Goeldi (MPEG),NaN,...,BRA,Brazil,BRA.14_1,Pará,BRA.14.78_2,Nova Ipixuna,NaN,NaN,NE,NaN
891,1438492471,Creative Commons Attribution Non Commercial (C...,NaN,NaN,CC_BY_NC_4_0,NaN,NaN,NaN,Museu Paraense Emílio Goeldi (MPEG),NaN,...,BRA,Brazil,BRA.14_1,Pará,BRA.14.78_2,Nova Ipixuna,NaN,NaN,NE,NaN

Retirando colunas sem registros

In [16]:
df = df.dropna(axis=1, how='all')

print(df.columns.tolist())

['gbifID', 'accessRights', 'license', 'rightsHolder', 'institutionCode', 'collectionCode', 'basisOfRecord', 'occurrenceID', 'catalogNumber', 'recordedBy', 'occurrenceStatus', 'preparations', 'eventDate', 'year', 'month', 'day', 'eventRemarks', 'higherGeography', 'continent', 'countryCode', 'stateProvince', 'county', 'locality', 'decimalLatitude', 'decimalLongitude', 'typeStatus', 'scientificName', 'kingdom', 'phylum', 'class', 'order', 'family', 'genus', 'genericName', 'specificEpithet', 'infraspecificEpithet', 'taxonRank', 'taxonomicStatus', 'datasetKey', 'publishingCountry', 'lastInterpreted', 'issue', 'hasCoordinate', 'hasGeospatialIssues', 'taxonKey', 'acceptedTaxonKey', 'kingdomKey', 'phylumKey', 'classKey', 'orderKey', 'familyKey', 'genusKey', 'speciesKey', 'species', 'acceptedScientificName', 'verbatimScientificName', 'protocol', 'lastParsed', 'lastCrawled', 'repatriated', 'level0Gid', 'level0Name', 'level1Gid', 'level1Name', 'level2Gid', 'level2Name', 'iucnRedListCategory']

Renomeando colunas com valores específicos do sql (evitando erros)

In [17]:
# Create a dictionary mapping old column names to new column names
rename_dict = {
    'class': 'TClass',
    'order': 'TOrder',
    'family': 'TFamily',
    'day': 'TDay',
    'month': 'TMonth',
    'year': 'TYear',
}

# Rename the columns
df.rename(columns=rename_dict, inplace=True)


print(df.columns.tolist())

['gbifID', 'accessRights', 'license', 'rightsHolder', 'institutionCode', 'collectionCode', 'basisOfRecord', 'occurrenceID', 'catalogNumber', 'recordedBy', 'occurrenceStatus', 'preparations', 'eventDate', 'TYear', 'TMonth', 'TDay', 'eventRemarks', 'higherGeography', 'continent', 'countryCode', 'stateProvince', 'county', 'locality', 'decimalLatitude', 'decimalLongitude', 'typeStatus', 'scientificName', 'kingdom', 'phylum', 'TClass', 'TOrder', 'TFamily', 'genus', 'genericName', 'specificEpithet', 'infraspecificEpithet', 'taxonRank', 'taxonomicStatus', 'datasetKey', 'publishingCountry', 'lastInterpreted', 'issue', 'hasCoordinate', 'hasGeospatialIssues', 'taxonKey', 'acceptedTaxonKey', 'kingdomKey', 'phylumKey', 'classKey', 'orderKey', 'familyKey', 'genusKey', 'speciesKey', 'species', 'acceptedScientificName', 'verbatimScientificName', 'protocol', 'lastParsed', 'lastCrawled', 'repatriated', 'level0Gid', 'level0Name', 'level1Gid', 'level1Name', 'level2Gid', 'level2Name', 'iucnRedListCategory']

C:\Users\jeffe\AppData\Local\Temp\ipykernel_16992\4247176367.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns=rename_dict, inplace=True)

Separando tabelas para o banco de dados

In [18]:
# Define the groups
groups = {
  'occurrencedetails': ['gbifID', 'accessRights', 'license', 'rightsHolder', 'institutionCode', 'collectionCode', 'basisOfRecord', 'occurrenceID', 'catalogNumber', 'recordedBy', 'occurrenceStatus', 'preparations', 'eventDate', 'TYear', 'TMonth', 'TDay', 'eventRemarks', 'higherGeography', 'continent', 'countryCode', 'stateProvince', 'county', 'locality', 'decimalLatitude', 'decimalLongitude', 'typeStatus'],
  'speciesinformation': ['gbifID', 'scientificName', 'kingdom', 'phylum', 'TClass', 'TOrder', 'TFamily', 'genus', 'genericName', 'specificEpithet', 'infraspecificEpithet', 'taxonRank', 'taxonomicStatus'],
  'datasetinformation': ['gbifID', 'datasetKey', 'publishingCountry', 'lastInterpreted', 'issue', 'hasCoordinate', 'hasGeospatialIssues'],
  'taxonomicinformation': ['gbifID', 'taxonKey', 'acceptedTaxonKey', 'kingdomKey', 'phylumKey', 'classKey', 'orderKey', 'familyKey', 'genusKey', 'speciesKey', 'species', 'acceptedScientificName', 'verbatimScientificName'],
  'protocolandiucninformation': ['gbifID', 'protocol', 'lastParsed', 'lastCrawled', 'repatriated', 'level0Gid', 'level0Name', 'level1Gid', 'level1Name', 'level2Gid', 'level2Name', 'iucnRedListCategory']
}

# Create a dictionary to hold the new DataFrames
dfs = {}

# Split the original DataFrame into smaller DataFrames based on the groups
for group_name, column_list in groups.items():
    dfs[group_name] = df[column_list]

CÓDIGO PARA CONECTAR COM O BANCO, postgres:senha@porta/nome-banco
TA CRIANDO UMA TABELA NO BANCO

In [6]:
# Função para criar conexão no banco
import psycopg2
def conecta_db():
  con = psycopg2.connect(host='localhost', 
                         database='dashboard',
                         user='postgres', 
                         password='dantas')
  return con

Função para criar tabela no banco

In [7]:
# Função para criar tabela no banco
def criar_db(sql):
  con = conecta_db()
  cur = con.cursor()
  cur.execute(sql)
  con.commit()
  con.close()

Criando tabelas

In [8]:
sql_occurrence_details = '''
CREATE TABLE OccurrenceDetails(
  gbifID                BIGINT NOT NULL PRIMARY KEY,
  accessRights          VARCHAR(240) NOT NULL,
  license               VARCHAR(240) NOT NULL,
  rightsHolder          VARCHAR(240) NOT NULL,
  institutionCode       VARCHAR(240) NOT NULL,
  collectionCode        VARCHAR(240) NOT NULL,
  basisOfRecord         VARCHAR(240) NOT NULL,
  occurrenceID          VARCHAR(240) NOT NULL,
  catalogNumber         VARCHAR(240) NOT NULL,
  recordedBy            VARCHAR(240),
  occurrenceStatus      VARCHAR(240) NOT NULL,
  preparations          VARCHAR(240),
  eventDate             VARCHAR(240),
  Tyear                VARCHAR(240),
  TMonth                VARCHAR(240),
  TDay                 VARCHAR(240),
  eventRemarks          VARCHAR(240),
  higherGeography       VARCHAR(240),
  continent             VARCHAR(240),
  countryCode           VARCHAR(240),
  stateProvince         VARCHAR(240),
  county                VARCHAR(240),
  locality              VARCHAR(240),
  decimalLatitude       NUMERIC(15,10),
  decimalLongitude      NUMERIC(15,10),
  typeStatus            VARCHAR(240)
);
'''

# SQL para criar a tabela TaxonomicInformation
sql_taxonomic_information = '''
CREATE TABLE TaxonomicInformation(
  gbifID                BIGINT NOT NULL PRIMARY KEY,
  taxonKey              INTEGER NOT NULL,
  acceptedTaxonKey      NUMERIC(15,2),
  kingdomKey            BIT NOT NULL,
  phylumKey             NUMERIC(15,2),
  classKey              NUMERIC(15,2),
  orderKey              NUMERIC(15,2),
  familyKey             NUMERIC(15,2),
  genusKey              NUMERIC(15,2),
  speciesKey            NUMERIC(15,2),
  species               VARCHAR(240),
  acceptedScientificName VARCHAR(240),
  verbatimScientificName VARCHAR(240),
  FOREIGN KEY (gbifID) REFERENCES OccurrenceDetails(gbifID)
);
'''

# SQL para criar a tabela SpeciesInformation
sql_species_information = '''
CREATE TABLE SpeciesInformation(
 gbifID                BIGINT NOT NULL PRIMARY KEY,
 scientificName        VARCHAR(240) NOT NULL,
 kingdom               VARCHAR(240) NOT NULL,
 phylum                VARCHAR(240),
 Tclass                VARCHAR(240),
 TOrder                VARCHAR(240),
 Tfamily               VARCHAR(240),
 genus                VARCHAR(240),
 genericName           VARCHAR(240),
 specificEpithet       VARCHAR(240),
 infraspecificEpithet  VARCHAR(240),
 taxonRank              VARCHAR(240) NOT NULL,
 taxonomicStatus       VARCHAR(240),
 FOREIGN KEY (gbifID) REFERENCES OccurrenceDetails(gbifID)
);
'''

# SQL para criar a tabela DatasetInformation
sql_dataset_information = '''
CREATE TABLE DatasetInformation(
 gbifID              BIGINT NOT NULL,
 datasetKey          VARCHAR(240) NOT NULL,
 publishingCountry   VARCHAR(240) NOT NULL,
 lastInterpreted     VARCHAR(240) NOT NULL,
 issue               VARCHAR(240) NOT NULL,
 hasCoordinate       VARCHAR(240) NOT NULL,
 hasGeospatialIssues VARCHAR(240) NOT NULL,
 FOREIGN KEY (gbifID) REFERENCES OccurrenceDetails(gbifID)
);
'''

# SQL para criar a tabela ProtocolAndIUCNInformation
sql_protocol_and_iucn_information = '''
CREATE TABLE ProtocolAndIUCNInformation(
 gbifID              BIGINT NOT NULL,
 protocol            VARCHAR(240) NOT NULL,
 lastParsed          VARCHAR(240) NOT NULL,
 lastCrawled         VARCHAR(240) NOT NULL,
 repatriated         VARCHAR(240),
 level0Gid           VARCHAR(240),
 level0Name          VARCHAR(240),
 level1Gid           VARCHAR(240),
 level1Name          VARCHAR(240),
 level2Gid           VARCHAR(240),
 level2Name          VARCHAR(240),
 iucnRedListCategory VARCHAR(240),
 FOREIGN KEY (gbifID) REFERENCES OccurrenceDetails(gbifID)
);
'''
criar_db(sql_occurrence_details)
criar_db(sql_taxonomic_information)
criar_db(sql_species_information)
criar_db(sql_dataset_information)
criar_db(sql_protocol_and_iucn_information)

Função para inserir dados no banco

In [9]:
# Função para inserir dados no banco
def inserir_db(sql):
    con = conecta_db()
    cur = con.cursor()
    try:
        cur.execute(sql)
        con.commit()
    except (Exception, psycopg2.DatabaseError) as error:
        print("Error: %s" % error)
        con.rollback()
        cur.close()
        return 1
    cur.close()

Realizando inserts, trocando valores vazios por null, nas tabelas.

In [10]:
df = dfs['occurrencedetails']

def format_value(value):
    if pd.isnull(value) or value == 'nan':
        return 'NULL'
    elif isinstance(value, str):
        return "'{}'".format(value)
    else:
        return str(value)

for i in df.index:
    values = [format_value(str(df[col][i])) for col in df.columns]
    insert_sql_occurrence_details = """
    INSERT into occurrencedetails ({}) 
    values({});
    """.format(', '.join(df.columns), ', '.join(values))
    inserir_db(insert_sql_occurrence_details)

In [11]:
df = dfs['taxonomicinformation']

def format_value(value):
    if pd.isnull(value) or value == 'nan':
        return 'NULL'
    elif isinstance(value, str):
        return "'{}'".format(value)
    else:
        return str(value)

for i in df.index:
    values = [format_value(str(df[col][i])) for col in df.columns]
    insert_sql_occurrence_details = """
    INSERT into taxonomicinformation ({}) 
    values({});
    """.format(', '.join(df.columns), ', '.join(values))
    inserir_db(insert_sql_occurrence_details)

In [12]:
df = dfs['speciesinformation']

def format_value(value):
    if pd.isnull(value) or value == 'nan':
        return 'NULL'
    elif isinstance(value, str):
        return "'{}'".format(value)
    else:
        return str(value)

for i in df.index:
    values = [format_value(str(df[col][i])) for col in df.columns]
    insert_sql_occurrence_details = """
    INSERT into speciesinformation ({}) 
    values({});
    """.format(', '.join(df.columns), ', '.join(values))
    inserir_db(insert_sql_occurrence_details)

In [13]:
df = dfs['datasetinformation']

def format_value(value):
    if pd.isnull(value) or value == 'nan':
        return 'NULL'
    elif isinstance(value, str):
        return "'{}'".format(value)
    else:
        return str(value)

for i in df.index:
    values = [format_value(str(df[col][i])) for col in df.columns]
    insert_sql_occurrence_details = """
    INSERT into datasetinformation ({}) 
    values({});
    """.format(', '.join(df.columns), ', '.join(values))
    inserir_db(insert_sql_occurrence_details)

In [14]:
df = dfs['protocolandiucninformation']

def format_value(value):
    if pd.isnull(value) or value == 'nan':
        return 'NULL'
    elif isinstance(value, str):
        return "'{}'".format(value)
    else:
        return str(value)

for i in df.index:
    values = [format_value(str(df[col][i])) for col in df.columns]
    insert_sql_occurrence_details = """
    INSERT into protocolandiucninformation ({}) 
    values({});
    """.format(', '.join(df.columns), ', '.join(values))
    inserir_db(insert_sql_occurrence_details)